---
- name: minikube-with-knative
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core

  vars:
    # to ensure we are on python3
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    # Default versions are v0.16.0, you can overide it using knative_serving_version, knative_eventing_version
    deploy_knative: True
    minikube_profile_name: my-demo

  roles:
    - role: kameshsampath.minikube
    - role: kameshsampath.k8s_app_spices
