---
- name: minikube-with-tektoncd
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core

  vars:
    # to ensure we are on python3
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    minikube_profile_name: my-demo
    deploy_tektoncd: True

  roles:
    - role: kameshsampath.minikube
    - role: kameshsampath.k8s_app_spices
